st_id, pre_st_ant, pre_st_post, pre_st_cervical, pre_st_am, 
			indirect_prep_imp, indirect_setting, 
			am, 
			tooth_colored_simple, tooth_colored_complex, tooth_colored_diastema, 
			post, core, 
			others, 
			surgery, miscellaneous, 
			pre_st_ant_pe, pre_st_ant_ce, pre_st_ant_cf, 
			pre_st_pre_pe, pre_st_pre_ce, pre_st_pre_cf, 
			pre_st_ant_re_rm, pre_st_ant_re_ce, pre_st_ant_re_cf, 
			pre_st_pre_re_rm, pre_st_pre_re_ce, pre_st_pre_re_cf, 
			endo_molar_pe, endo_molar_ce, endo_molar_cf, endo_molar_etc, 
			endo_pre_pe, endo_pre_ce, endo_pre_cf, endo_pre_etc, 
			endo_ant_pe, endo_ant_ce, endo_ant_cf, endo_ant_etc, 
			st_op_tooth_colored_cervical, st_op_tooth_colored_simple, 
			st_op_tooth_colored_complex, st_op_tooth_colored_diastema, 
			st_op_am_simple, st_op_am_complex, st_op_bleaching, st_op_others, 
			st_endo_point,
			date_update
'admin', '0', '0', '0', '0','0', '0','0','0', '0', '0','0', '0', '0','0', '0','0', '0', '0','0', '0', '0','0', '0', '0','0', '0', '0','0', '0', '0', '0','0', '0', '0', '0','0', '0', '0', '0','0', '0','0', '0','0', '0','0', '0','0','20130720204722'